### ISSUE TITLE
How to bring back animation borderless win form in minimize and maximize in vb .net?

### ISSUE THREAD

**Issue by VahidEra** [mganss/BorderlessForm#4]
How do I bring back animation borderless win form in minimize and maximize in Visual Basic
of course, there is a Nice solution to this problem which you can see in [here](https://github.com/mganss/BorderlessForm) 
but it is in C# language and I want it in Visual Basic language. I've converted before with the language converter, but it's not right.
Can you help me please?

**Comment by mganss** [comment]
I don't know VB.NET. Perhaps you can put the C# code in its own project within your solution and add a reference to the C# project from a VB.NET project.

**Comment by VahidEra** [comment]
> 
> 
> I don't know VB.NET. Perhaps you can put the C# code in its own project within your solution and add a reference to the C# project from a VB.NET project.

Thank you for help, dear mganss
